{"CVE_APLICACION":"Dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"Dummy","DESC_ERROR":"No existe valor para llave primaria  CVE_USUARIO ","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-29T21:51:03.617Z","ID_EVENTO":7329,"ID_PROCESO":14,"MSG_ERROR":"Error de tipo string en Proceso login: 'No existe valor para llave primaria  CVE_USUARIO '.","level":"error","message":"Error ","timestamp":"2025-08-29 15:51:03"}
{"CVE_APLICACION":"Dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"Dummy","DESC_ERROR":"No existe valor para llave primaria  CVE_USUARIO ","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-29T21:51:03.654Z","ID_EVENTO":7330,"ID_PROCESO":14,"MSG_ERROR":"Error de tipo string en Proceso de Login: 'No existe valor para llave primaria  CVE_USUARIO '.","level":"error","message":"Error ","timestamp":"2025-08-29 15:51:03"}
{"CVE_APLICACION":"Dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"Dummy","DESC_ERROR":"No existe valor para llave primaria  CVE_USUARIO ","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-30T23:57:29.803Z","ID_EVENTO":7331,"ID_PROCESO":8,"MSG_ERROR":"Error de tipo string en Proceso login: 'No existe valor para llave primaria  CVE_USUARIO '.","level":"error","message":"Error ","timestamp":"2025-08-30 17:57:29"}
{"CVE_APLICACION":"Dummy","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"Dummy","DESC_ERROR":"No existe valor para llave primaria  CVE_USUARIO ","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-30T23:57:29.849Z","ID_EVENTO":7332,"ID_PROCESO":8,"MSG_ERROR":"Error de tipo string en Proceso de Login: 'No existe valor para llave primaria  CVE_USUARIO '.","level":"error","message":"Error ","timestamp":"2025-08-30 17:57:29"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: \"undefined\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:45:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-30T23:57:51.184Z","ID_EVENTO":7333,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-08-30 17:57:51"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: \"undefined\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:45:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-30T23:58:37.726Z","ID_EVENTO":7334,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-08-30 17:58:37"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: \"undefined\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:45:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-30T23:58:46.256Z","ID_EVENTO":7335,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-08-30 17:58:46"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: \"undefined\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:45:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-30T23:59:00.962Z","ID_EVENTO":7336,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-08-30 17:59:00"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: \"undefined\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:45:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-30T23:59:13.957Z","ID_EVENTO":7337,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-08-30 17:59:13"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: \"undefined\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:45:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T00:00:39.680Z","ID_EVENTO":7338,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-08-30 18:00:39"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: \"undefined\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:45:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T00:01:38.753Z","ID_EVENTO":7339,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-08-30 18:01:38"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: \"undefined\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:45:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T00:06:54.795Z","ID_EVENTO":7340,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-08-30 18:06:54"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: \"undefined\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:46:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T00:09:38.117Z","ID_EVENTO":7341,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-08-30 18:09:38"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"SyntaxError: \"undefined\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at login (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/login.js:46:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlLogin (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contLogin.js:18:24)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T00:10:48.564Z","ID_EVENTO":7342,"ID_PROCESO":1,"MSG_ERROR":"Error desconocido en Proceso de Login: {}.","level":"error","message":"Error ","timestamp":"2025-08-30 18:10:48"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"No existe valor para llave primaria  ID_QUINIELA ","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T01:01:58.846Z","ID_EVENTO":7343,"ID_PROCESO":7,"MSG_ERROR":"Error de tipo string en Ejecucion Crud/Bulk Update: 'No existe valor para llave primaria  ID_QUINIELA '.","level":"error","message":"Error ","timestamp":"2025-08-30 19:01:58"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:35:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contProcedure.js:16:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T01:08:18.157Z","ID_EVENTO":7345,"ID_PROCESO":9,"MSG_ERROR":"DatabaseError en Ejecucion de Procedimiento. Mensaje de Sequelize: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. Mensaje original de DB: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. SQL: 'exec spAbreQuin @pIdQuiniela = 1, @pIdPeriodo = '12', @pHeader = '{\"idProceso\":9,\"cveAplicacion\":\"NFL\",\"cveUsuario\":\"mario@quiniela.com\",\"cveIdioma\":\"ES\",\"cvePerfil\":\"SISTEMAS\"}''","level":"error","message":"Error ","timestamp":"2025-08-30 19:08:18"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:35:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contProcedure.js:16:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T01:08:20.254Z","ID_EVENTO":7347,"ID_PROCESO":9,"MSG_ERROR":"DatabaseError en Ejecucion de Procedimiento. Mensaje de Sequelize: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. Mensaje original de DB: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. SQL: 'exec spAbreQuin @pIdQuiniela = 1, @pIdPeriodo = '12', @pHeader = '{\"idProceso\":9,\"cveAplicacion\":\"NFL\",\"cveUsuario\":\"mario@quiniela.com\",\"cveIdioma\":\"ES\",\"cvePerfil\":\"SISTEMAS\"}''","level":"error","message":"Error ","timestamp":"2025-08-30 19:08:20"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:35:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contProcedure.js:16:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T01:08:20.809Z","ID_EVENTO":7349,"ID_PROCESO":9,"MSG_ERROR":"DatabaseError en Ejecucion de Procedimiento. Mensaje de Sequelize: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. Mensaje original de DB: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. SQL: 'exec spAbreQuin @pIdQuiniela = 1, @pIdPeriodo = '12', @pHeader = '{\"idProceso\":9,\"cveAplicacion\":\"NFL\",\"cveUsuario\":\"mario@quiniela.com\",\"cveIdioma\":\"ES\",\"cvePerfil\":\"SISTEMAS\"}''","level":"error","message":"Error ","timestamp":"2025-08-30 19:08:20"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:35:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contProcedure.js:16:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T01:08:21.267Z","ID_EVENTO":7351,"ID_PROCESO":9,"MSG_ERROR":"DatabaseError en Ejecucion de Procedimiento. Mensaje de Sequelize: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. Mensaje original de DB: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. SQL: 'exec spAbreQuin @pIdQuiniela = 1, @pIdPeriodo = '12', @pHeader = '{\"idProceso\":9,\"cveAplicacion\":\"NFL\",\"cveUsuario\":\"mario@quiniela.com\",\"cveIdioma\":\"ES\",\"cvePerfil\":\"SISTEMAS\"}''","level":"error","message":"Error ","timestamp":"2025-08-30 19:08:21"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:35:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contProcedure.js:16:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T01:08:21.791Z","ID_EVENTO":7353,"ID_PROCESO":9,"MSG_ERROR":"DatabaseError en Ejecucion de Procedimiento. Mensaje de Sequelize: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. Mensaje original de DB: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. SQL: 'exec spAbreQuin @pIdQuiniela = 1, @pIdPeriodo = '12', @pHeader = '{\"idProceso\":9,\"cveAplicacion\":\"NFL\",\"cveUsuario\":\"mario@quiniela.com\",\"cveIdioma\":\"ES\",\"cvePerfil\":\"SISTEMAS\"}''","level":"error","message":"Error ","timestamp":"2025-08-30 19:08:21"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:35:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contProcedure.js:16:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T01:08:22.356Z","ID_EVENTO":7355,"ID_PROCESO":9,"MSG_ERROR":"DatabaseError en Ejecucion de Procedimiento. Mensaje de Sequelize: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. Mensaje original de DB: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. SQL: 'exec spAbreQuin @pIdQuiniela = 1, @pIdPeriodo = '12', @pHeader = '{\"idProceso\":9,\"cveAplicacion\":\"NFL\",\"cveUsuario\":\"mario@quiniela.com\",\"cveIdioma\":\"ES\",\"cvePerfil\":\"SISTEMAS\"}''","level":"error","message":"Error ","timestamp":"2025-08-30 19:08:22"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:35:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contProcedure.js:16:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T01:08:22.861Z","ID_EVENTO":7357,"ID_PROCESO":9,"MSG_ERROR":"DatabaseError en Ejecucion de Procedimiento. Mensaje de Sequelize: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. Mensaje original de DB: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. SQL: 'exec spAbreQuin @pIdQuiniela = 1, @pIdPeriodo = '12', @pHeader = '{\"idProceso\":9,\"cveAplicacion\":\"NFL\",\"cveUsuario\":\"mario@quiniela.com\",\"cveIdioma\":\"ES\",\"cvePerfil\":\"SISTEMAS\"}''","level":"error","message":"Error ","timestamp":"2025-08-30 19:08:22"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:35:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contProcedure.js:16:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T01:08:23.777Z","ID_EVENTO":7359,"ID_PROCESO":9,"MSG_ERROR":"DatabaseError en Ejecucion de Procedimiento. Mensaje de Sequelize: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. Mensaje original de DB: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. SQL: 'exec spAbreQuin @pIdQuiniela = 1, @pIdPeriodo = '12', @pHeader = '{\"idProceso\":9,\"cveAplicacion\":\"NFL\",\"cveUsuario\":\"mario@quiniela.com\",\"cveIdioma\":\"ES\",\"cvePerfil\":\"SISTEMAS\"}''","level":"error","message":"Error ","timestamp":"2025-08-30 19:08:23"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ExecQuery (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:42:23)\n    at async ExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/ProcSql.js:35:23)\n    at async ejecFuncion (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Util/utilComun.js:14:16)\n    at async ctrlExecProcedure (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Controler/contProcedure.js:16:29)","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T01:12:05.214Z","ID_EVENTO":7361,"ID_PROCESO":9,"MSG_ERROR":"DatabaseError en Ejecucion de Procedimiento. Mensaje de Sequelize: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. Mensaje original de DB: 'The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_Q_QUIN_P_REF_Q_PARTID\". The conflict occurred in database \"NFLQUIN\", table \"dbo.Q_PARTIDO\".'. SQL: 'exec spAbreQuin @pIdQuiniela = 1, @pIdPeriodo = '12', @pHeader = '{\"idProceso\":9,\"cveAplicacion\":\"NFL\",\"cveUsuario\":\"mario@quiniela.com\",\"cveIdioma\":\"ES\",\"cvePerfil\":\"SISTEMAS\"}''","level":"error","message":"Error ","timestamp":"2025-08-30 19:12:05"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"Ha ocurrido un error inesperado.","ERROR_LINE_D":null,"ERROR_MESSAGE_D":"Error\n    at Query.run (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:107:25)\n    at C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MSSqlQueryInterface.bulkUpdate (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:366:12)\n    at async Q_QUIN_PARTICIPANTE.update (C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\model.js:2010:28)\n    at async file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:55:30\n    at async obtResultado (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:123:27)\n    at async updateRecord (file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:54:27)\n    at async file:///C:/ZG/Proyectos/Desarrollo/Poyectos%20Nucleo/API/lib_comun/dist/Router/Servicios/actualizaBD.js:104:31\n    at async C:\\ZG\\Proyectos\\Desarrollo\\Poyectos Nucleo\\API\\lib_comun\\node_modules\\sequelize\\lib\\sequelize.js:507:18","ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T16:59:29.809Z","ID_EVENTO":7362,"ID_PROCESO":2,"MSG_ERROR":"DatabaseError en Ejecucion Crud/Bulk Update. Mensaje de Sequelize: 'String or binary data would be truncated.'. Mensaje original de DB: 'String or binary data would be truncated.'. SQL: 'UPDATE [dbo].[Q_QUIN_PARTICIPANTE] SET [ID_QUINIELA]=@0,[ID_PARTICIPANTE]=@1,[ID_PERIODO]=@2,[ID_PARTIDO]=@3,[CVE_GANADOR]=@4 WHERE [ID_QUINIELA] = @5 AND [ID_PARTICIPANTE] = @6 AND [ID_PERIODO] = @7 AND [ID_PARTIDO] = @8'","level":"error","message":"Error ","timestamp":"2025-08-31 10:59:29"}
{"CVE_APLICACION":"NFL","CVE_TIPO_EVENTO":"E","CVE_USUARIO":"mario@quiniela.com","DESC_ERROR":"No existen datos a actualizar","ERROR_LINE_D":null,"ERROR_MESSAGE_D":null,"ERROR_NUMBER_D":null,"ERROR_PROCEDURE_D":null,"ERROR_SEVERITY_D":null,"ERROR_STATE_D":null,"F_EVENTO":"2025-08-31T17:36:47.661Z","ID_EVENTO":7363,"ID_PROCESO":7,"MSG_ERROR":"Error de tipo string en Ejecucion Crud/Bulk Update: 'No existen datos a actualizar'.","level":"error","message":"Error ","timestamp":"2025-08-31 11:36:47"}
